site_name: NetLinx Language Help
site_description: Help reference for the NetLinx programming language.
site_url: https://norgate-av.github.io/netlinx-help
repo_url: https://github.com/Norgate-AV/netlinx-help
repo_name: norgate-av/netlinx-help

plugins:
  - optimize
  - search
  - social
  - tags

extra:
  version:
    provider: mike
    default: stable

theme:
  name: material

  language: en

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - content.action.edit
    - content.code.copy
    - content.code.select
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: indigo
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: indigo
      accent: deep purple

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details

nav:
  - Home: index.md
  - Language Elements:
      - Mainline: Language-Elements/Mainline.md
      - Statements and Expressions: Language-Elements/Statements_and_Expressions.md
      - Keywords: Language-Elements/Keywords.md
      - Devices: Language-Elements/Devices.md
      - Device Numbers - Supported Ranges by Device Type: Language-Elements/Device_Numbers-_Supported_Ranges_by_Device_Type.md
      - Virtual Devices: Language-Elements/Virtual_Devices.md
      - Comments: Language-Elements/Comments.md
      - Identifiers:
          - Language-Elements/Identifiers/index.md
          - Devices: Language-Elements/Devices.md
          - Device Arrays: Language-Elements/Identifiers/Device_Arrays.md
          - Device-Channels and Device-Channel Arrays: Language-Elements/Identifiers/Device_Channels_and_Device_Channel_Arrays.md
          - Device-Level Arrays: Language-Elements/Identifiers/Device_Level_Arrays.md
          - Data Sets: Language-Elements/Identifiers/Data_Set_Structures.md
          - Virtual Devices: Language-Elements/Virtual_Devices.md
      - Variables & Constants:
          - Language-Elements/Variables-Constants/index.md
          - Variables: Language-Elements/Variables-Constants/Variables.md
          - Local Variables: Language-Elements/Variables-Constants/Local_Variables.md
          - Global Variables: Language-Elements/Variables-Constants/Global_Variables.md
          - Persistant Variables: Language-Elements/Variables-Constants/Persistent_Variables.md
          - Variables Keywords: Language-Elements/Variables-Constants/Variables_Keywords.md
          - DEFINE_MUTUALLY_EXCLUSIVE and Variables: Language-Elements/Variables-Constants/DEFINE_MUTUALLY_EXCLUSIVE_and_Variables.md
          - Constants: Language-Elements/Variables-Constants/Constants.md
      - Subroutines (Functions):
          - Language-Elements/Subroutines-Functions/index.md
          - Subroutines - Calling Paramaters: Language-Elements/Subroutines-Functions/Subroutines_-_Calling_Parameters.md
          - Subroutines - Return Statements: Language-Elements/Subroutines-Functions/Subroutines_-_Return_Statements.md
          - SYSTEM_CALL Subroutines: Language-Elements/Subroutines-Functions/System_Call_Subroutines.md
          - Subroutine Keywords: Language-Elements/Subroutines-Functions/Subroutine_Keywords.md
      - Compiler Directives:
          - Language-Elements/Compiler-Directives/index.md
          - "#DEFINE": Language-Elements/Compiler-Directives/_DEFINE.md
          - "#DISABLE_WARNING": Language-Elements/Compiler-Directives/_DISABLE_WARNING_.md
          - "#ELSE": Language-Elements/Compiler-Directives/_ELSE.md
          - "#END_IF": Language-Elements/Compiler-Directives/_END_IF.md
          - "#IF_DEFINED": Language-Elements/Compiler-Directives/_IF_DEFINED.md
          - "#IF_NOT_DEFINED": Language-Elements/Compiler-Directives/_IF_NOT_DEFINED.md
          - "#INCLUDE": Language-Elements/Compiler-Directives/_INCLUDE.md
          - "#WARN": Language-Elements/Compiler-Directives/_WARN.md
      - Arrays:
          - Language-Elements/Arrays/index.md
          - Multi-Dimensional Arrays: Language-Elements/Arrays/Multi_Dimensional_Arrays.md
          - Device Arrays: Language-Elements/Arrays/Device_Arrays.md
          - Device-Level Arrays: Language-Elements/Arrays/Device_Level_Arrays.md
          - Device-Channels and Device-Channel Arrays: Language-Elements/Arrays/Device_Channels_and_Device_Channel_Arrays.md
          - Array Keywords: Language-Elements/Arrays/Array_Keywords.md
      - Assignments:
          - Language-Elements/Assignments/index.md
          - Variables: Language-Elements/Assignments/Variables.md
          - Output Channels: Language-Elements/Assignments/Output_channels.md
      - Data Types:
          - Intrinsic Data Types: Language-Elements/Data-Types/Intrinsic_Data_Types.md
          - Custom Data Types: Language-Elements/Data-Types/Custom_Data_Types.md
          - Data Type Conversion: Language-Elements/Data-Types/Data_Type_Conversion.md
          - Data Type Keywords: Language-Elements/Data-Types/Data_Type_Keywords.md
      - Event Handlers:
          - Language-Elements/Event-Handlers/index.md
          - Button Events: Language-Elements/Event-Handlers/Button_Events.md
          - Channel Events: Language-Elements/Event-Handlers/Channel_Events.md
          - Data Events: Language-Elements/Event-Handlers/Data_Events.md
          - Level Events: Language-Elements/Event-Handlers/Level_Events.md
          - Event Parameters: Language-Elements/Event-Handlers/Event_Parameters.md
          - Custom Events: Language-Elements/Event-Handlers/Custom_Events.md
          - Event Handler Keywords: Language-Elements/Event-Handlers/Event_Handler_Keywords.md
