site_name: NetLinx Language Help
site_description: Help reference for the NetLinx programming language.
site_url: https://norgate-av.github.io/netlinx-help
repo_url: https://github.com/Norgate-AV/netlinx-help
repo_name: norgate-av/netlinx-help

plugins:
  - optimize
  - search
  - social
  - tags

extra:
  version:
    provider: mike
    default: stable

theme:
  name: material

  language: en

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - content.action.edit
    - content.code.copy
    - content.code.select
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: indigo
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: indigo
      accent: deep purple

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details

nav:
  - Home: index.md
  - Language Elements:
      - Mainline: Language-Elements/Mainline.md
      - Statements and Expressions: Language-Elements/Statements_and_Expressions.md
      - Keywords: Language-Elements/Keywords.md
      - Devices: Language-Elements/Devices.md
      - Device Numbers - Supported Ranges by Device Type: Language-Elements/Device_Numbers-_Supported_Ranges_by_Device_Type.md
      - Virtual Devices: Language-Elements/Virtual_Devices.md
      - Comments: Language-Elements/Comments.md
      - Identifiers:
          - Language-Elements/Identifiers/index.md
          - Devices: Language-Elements/Devices.md
          - Device Arrays: Language-Elements/Identifiers/Device_Arrays.md
          - Device-Channels and Device-Channel Arrays: Language-Elements/Identifiers/Device_Channels_and_Device_Channel_Arrays.md
          - Device-Level Arrays: Language-Elements/Identifiers/Device_Level_Arrays.md
          - Data Sets: Language-Elements/Identifiers/Data_Set_Structures.md
          - Virtual Devices: Language-Elements/Virtual_Devices.md
      - Variables & Constants:
          - Language-Elements/Variables-Constants/index.md
          - Variables: Language-Elements/Variables-Constants/Variables.md
          - Local Variables: Language-Elements/Variables-Constants/Local_Variables.md
          - Global Variables: Language-Elements/Variables-Constants/Global_Variables.md
          - Persistant Variables: Language-Elements/Variables-Constants/Persistent_Variables.md
          - Variables Keywords: Language-Elements/Variables-Constants/Variables_Keywords.md
          - DEFINE_MUTUALLY_EXCLUSIVE and Variables: Language-Elements/Variables-Constants/DEFINE_MUTUALLY_EXCLUSIVE_and_Variables.md
          - Constants: Language-Elements/Variables-Constants/Constants.md
      - Subroutines (Functions):
          - Language-Elements/Subroutines-Functions/index.md
          - Subroutines - Calling Paramaters: Language-Elements/Subroutines-Functions/Subroutines_-_Calling_Parameters.md
          - Subroutines - Return Statements: Language-Elements/Subroutines-Functions/Subroutines_-_Return_Statements.md
          - SYSTEM_CALL Subroutines: Language-Elements/Subroutines-Functions/System_Call_Subroutines.md
          - Subroutine Keywords: Language-Elements/Subroutines-Functions/Subroutine_Keywords.md
      - Compiler Directives:
          - Language-Elements/Compiler-Directives/index.md
          - "#DEFINE": Language-Elements/Compiler-Directives/_DEFINE.md
          - "#DISABLE_WARNING": Language-Elements/Compiler-Directives/_DISABLE_WARNING_.md
          - "#ELSE": Language-Elements/Compiler-Directives/_ELSE.md
          - "#END_IF": Language-Elements/Compiler-Directives/_END_IF.md
          - "#IF_DEFINED": Language-Elements/Compiler-Directives/_IF_DEFINED.md
          - "#IF_NOT_DEFINED": Language-Elements/Compiler-Directives/_IF_NOT_DEFINED.md
          - "#INCLUDE": Language-Elements/Compiler-Directives/_INCLUDE.md
          - "#WARN": Language-Elements/Compiler-Directives/_WARN.md
      - Arrays:
          - Language-Elements/Arrays/index.md
          - Multi-Dimensional Arrays: Language-Elements/Arrays/Multi_Dimensional_Arrays.md
          - Device Arrays: Language-Elements/Arrays/Device_Arrays.md
          - Device-Level Arrays: Language-Elements/Arrays/Device_Level_Arrays.md
          - Device-Channels and Device-Channel Arrays: Language-Elements/Arrays/Device_Channels_and_Device_Channel_Arrays.md
          - Array Keywords: Language-Elements/Arrays/Array_Keywords.md
      - Assignments:
          - Language-Elements/Assignments/index.md
          - Variables: Language-Elements/Assignments/Variables.md
          - Output Channels: Language-Elements/Assignments/Output_channels.md
      - Data Types:
          - Intrinsic Data Types: Language-Elements/Data-Types/Intrinsic_Data_Types.md
          - Custom Data Types: Language-Elements/Data-Types/Custom_Data_Types.md
          - Data Type Conversion: Language-Elements/Data-Types/Data_Type_Conversion.md
          - Data Type Keywords: Language-Elements/Data-Types/Data_Type_Keywords.md
      - Event Handlers:
          - Language-Elements/Event-Handlers/index.md
          - Button Events: Language-Elements/Event-Handlers/Button_Events.md
          - Channel Events: Language-Elements/Event-Handlers/Channel_Events.md
          - Data Events: Language-Elements/Event-Handlers/Data_Events.md
          - Level Events: Language-Elements/Event-Handlers/Level_Events.md
          - Event Parameters: Language-Elements/Event-Handlers/Event_Parameters.md
          - Custom Events: Language-Elements/Event-Handlers/Custom_Events.md
          - Event Handler Keywords: Language-Elements/Event-Handlers/Event_Handler_Keywords.md
      - Loops:
          - Language-Elements/Loops/index.md
          - FOR Loops: Language-Elements/Loops/FOR_loops.md
          - Conditional Keywords: Language-Elements/Loops/Conditional_Keywords.md
      - Strings:
          - Language-Elements/Strings/index.md
          - Wide strings: Language-Elements/Strings/Wide_Strings.md
          - STRING Keywords: Language-Elements/Strings/STRING_Keywords.md
      - Structures:
          - Language-Elements/Structures/index.md
          - Data Set Structures: Language-Elements/Structures/Data_Set_Structures.md
      - Timelines:
          - Timeline Functions: Language-Elements/Timelines/Timeline_Functions.md
          - TIMELINE IDs: Language-Elements/Timelines/TIMELINE_IDs.md
          - TIMELINE Example: Language-Elements/Timelines/TIMELINE_example.md
          - TIMELINE Keywords: Language-Elements/Timelines/TIMELINE_Keywords.md
      - Waits:
          - Language-Elements/Waits/index.md
          - Timed Waits: Language-Elements/Waits/Timed_Waits.md
          - Conitional Waits: Language-Elements/Waits/Conditional_Waits.md
          - Timed Conditional Waits: Language-Elements/Waits/Timed_Conditional_Waits.md
          - WAIT Keywords: Language-Elements/Waits/WAIT_Keywords.md
  - Combining Devices, Levels, and Channels:
      - Combining-Devices-Levels-Channels/index.md
      - Combining and Uncombining Channels: Combining-Devices-Levels-Channels/Combining_and_Uncombining_Channels.md
      - Combining and Uncombining Devices: Combining-Devices-Levels-Channels/Combining_and_Uncombining_Devices.md
      - Combining and Uncombining Levels: Combining-Devices-Levels-Channels/Combining_and_Uncombining_Levels.md
      - Combine and Uncombine Keywords: Combining-Devices-Levels-Channels/COMBINE_&_UNCOMBINE_Keywords.md
      - Virtual Devices: Combining-Devices-Levels-Channels/Virtual_Devices.md
  - IP Communication:
      - IP-Communication/index.md
      - Client Programming: IP-Communication/Client_Programming.md
      - Server Programming: IP-Communication/Server_Programming.md
      - Receiving Data with UDP: IP-Communication/Receiving_Data_with_UDP.md
      - Multicast UDP Messages: IP-Communication/Multicast_UDP_Messages.md
      - Example IP Code: IP-Communication/Example_IP_Code.md
      - IP Keywords: IP-Communication/IP_Keywords.md
  - NetLinx Modules:
      - NetLinx-Modules/index.md
      - Defining a Module: NetLinx-Modules/Defining_a_Module.md
      - Module Keywords: NetLinx-Modules/Module_Keywords.md
  - Unicode:
      - Working With Unicode: Unicode/Working_With_UniCode.md
      - Working With WIDECHAR arrays and Unicode Strings: Unicode/Working_with_WIDECHAR_arrays_and_Unicode_Strings.md
      - Reading and Writing to Files: Unicode/Reading_and_Writing_to_Files.md
      - Unicode-Related Compiler Errors: Unicode/Unicode-Related_Compiler_Errors.md
  - Master-To-Master (M2M):
      - Master-To-Master/index.md
      - Design Considerations, Constraints, and Topologies:
          - M2M - Design Considerations, Constraints, and Topologies: Master-To-Master/Design-Constraints-Topologies/index.md
          - M2M - Design Topologies:
              - Master-To-Master/Design-Constraints-Topologies/Design-Topologies/index.md
  - Marshalling Protocol:
      - Marshalling-Protocol/index.md
      - Marshalling Protocol (Group of Bytes): Marshalling-Protocol/Marshalling_Protocol_Group_of_Bytes_.md
      - Marshalling Protocol (Variables): Marshalling-Protocol/Marshalling_Protocol_Variables_.md
      - "Marshalling Protocol: Encoding Notes": Marshalling-Protocol/Marshalling_Protocol_Encoding_Notes.md
      - String Encoding: Marshalling-Protocol/String_Encoding.md
      - Binary Array Encoding: Marshalling-Protocol/Binary_Array_Encoding.md
  - ASCII /HEX /Decimal Conversions Table:
      - ASCII-Hex-Decimal-Conversion/index.md
