[project]
name = "netlinx-help"
version = "0.1.0"
description = "Documentation for NetLinx"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mike>=2.1.3",
    "mkdocs-material[imaging]>=9.7.0",
]
